%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\NGGM3KQ\Documents\MATLAB\AstroPiData\Columbus_Ed_astro_pi_datalog_2weeks.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/05/18 10:51:02

%% Initialize variables.
filename = 'C:\Users\NGGM3KQ\Documents\MATLAB\AstroPiData\Columbus2_Ed_astro_pi_datalog_4weeks.csv';
delimiter = ',';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: datetimes (%{yyyy-MM-dd HH:mm:ss}D)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%{yyyy-MM-dd HH:mm:ss}D%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
AstroPiData = table(dataArray{1:end-1}, 'VariableNames', {'ROW_ID','temp_cpu','temp_h','temp_p','humidity','pressure','pitch','roll','yaw','mag_x','mag_y','mag_z','accel_x','accel_y','accel_z','gyro_x','gyro_y','gyro_z','reset','time_stamp'});

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% ColumbusEdastropidatalog2weeks.time_stamp=datenum(ColumbusEdastropidatalog2weeks.time_stamp);

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;